import "../styles/globals.css";
import Navbar from "./components/Navbar";
import Provider from "./components/ProviderDarkTheme";
import { Nanum_Gothic_Coding } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Nanum_Gothic_Coding({
  weight: "700",
  subsets: ["latin"],
  display: "swap",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={font.className} suppressHydrationWarning>
      <body>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
